Smart_Attendance_System/Smart_Attendance_System/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^face_recognition/', include('face_recognition.urls')),
    url(r'^admin_cpanel/', include('admin_cpanel.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls')),
    url(r'^', include('home.urls')),     # Seperate App
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^disclaimer/', include('disclaimer.urls')),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'mark_attendance', include('mark_attendance.urls')),
    url(r'fetch_data', include('fetch_data.urls')),
    url(r'^terms_and_conditions', include('terms_and_conditions.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Smart_Attendance_System/fetch_data/urls.py
from django.conf.urls import url

from . import views

app_name = 'fetch_data'

urlpatterns = [
    url(r'^$', views.fetch_data, name="fetch_data"),
]

Smart_Attendance_System/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Smart_Attendance_System/fetch_data/models.py
from django.db import models

# Create your models here.

Smart_Attendance_System/fetch_data/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import trigger


@login_required(login_url="/accounts/login/")
def fetch_data(request):
    # return render(request, 'fetch_data/fetch_data.html')
    if request.POST:
        roll_no = request.POST['term']
        enrollment_no, name, total_days, total_present_days, percentage = trigger.start(roll_no)
        enrollment_no = str(enrollment_no)
        total_days = str(total_days)
        total_present_days = str(total_present_days)
        percentage = str(percentage)
        data = {'data': '1',
                'name': name,
                'enrollment_no': enrollment_no,
                'total_days': total_days,
                'total_present_days': total_present_days,
                'percentage': percentage,
               }
        return render(request, 'fetch_data/fetch_data_result.html', data)
    else:
        return render(request, 'fetch_data/fetch_data.html')

Smart_Attendance_System/fetch_data/templates/fetch_data/fetch_data.html
{% extends 'base_layout2.html' %}

{% block fetch_data %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Fetch Data</h1>
    <div class="create-article">
        <form action="{% url 'fetch_data:fetch_data' %}" method="post">
            <input type="text" name="term" size="30"> <input type="submit" value="Search">
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

Smart_Attendance_System/fetch_data/templates/fetch_data/fetch_data_result.html
{% extends 'base_layout2.html' %}

{% block fetch_data %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Fetched Data Result-</h1>
        <!--{% for key, value in data.items %}-->
          <!--<li>{{ key }} : {{ value }}</li>-->
        <!--{% endfor %}-->

         {% if data %}
            <!--{{ data.keys }}-->
            {% for i in data %}
                <p><b>Enrollment Number: {{ enrollment_no }}</b></p>
                <p>Name: {{ name }}</p>
                <p>Total Days: {{ total_days }}</p>
                <p>Total Present Days: {{ total_present_days }}</p>
                <p>Percentage: {{ percentage }}</p>
            {% endfor %}
         {% endif %}

{% endblock %}