Smart_Attendance_System/Smart_Attendance_System/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^face_recognition/', include('face_recognition.urls')),
    url(r'^admin_cpanel/', include('admin_cpanel.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls')),
    url(r'^', include('home.urls')),     # Seperate App
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^disclaimer/', include('disclaimer.urls')),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'mark_attendance', include('mark_attendance.urls')),
    url(r'fetch_data', include('fetch_data.urls')),
    url(r'^terms_and_conditions', include('terms_and_conditions.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Smart_Attendance_System/admin_cpanel/urls.py
from django.conf.urls import url

from . import views


app_name = 'admin_cpanel'

urlpatterns = [
    url(r'^', views.admin_cpanel, name="admin_cpanel"),
]

Smart_Attendance_System/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Smart_Attendance_System/admin_cpanel/models.py
from django.db import models


# Create your models here.
class UploadFile(models.Model):
    file = models.FileField(blank=False)

Smart_Attendance_System/admin_cpanel/forms.py
from django import forms
from . import models


class UploadFile(forms.ModelForm):
    class Meta:
        model = models.UploadFile
        fields = ['file']

Smart_Attendance_System/admin_cpanel/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms


@login_required(login_url="/accounts/login/")
def admin_cpanel(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = forms.UploadFile(request.POST, request.FILES)
            if form.is_valid():
                # save article to db
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect('face_recognition:face_recognition')
        else:
            form = forms.UploadFile()
        return render(request, 'admin_cpanel/admin_cpanel.html', {'form': form})
    else:
        return render(request, 'admin_cpanel/not_valid_user.html')

Smart_Attendance_System/admin_cpanel/templates/admin_cpanel/admin_cpanel.html
{% extends 'base_layout2.html' %}

{% block admin_cpanel %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>CPanel</h1>
    <h4 style="color: #212529">In Cpanel only Admin can submit .xlsx(excel) file for Training</h4>
    <h5 style="color: #212529">Once you upload file you can start Training of dataset from next page</h5>
    <div class="create-article">
        <form class="site-form" action="{% url 'admin_cpanel:admin_cpanel' %}" method="post" enctype="multipart/form-data">
            <h2 style="color: red">Submit Your File (file must be .xlsx)</h2>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

Smart_Attendance_System/admin_cpanel/templates/admin_cpanel/not_valid_user.html
{% extends 'base_layout2.html' %}


{% block articleCreateli %} class="nav-item active" {% endblock %}

{% block content %}
    <div class="create-article">
        <h1>You are not a valid user, contact administrator or go back to home</h1>
    </div>
{% endblock %}