Smart_Attendance_System/Smart_Attendance_System/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^face_recognition/', include('face_recognition.urls')),
    url(r'^admin_cpanel/', include('admin_cpanel.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls')),
    url(r'^', include('home.urls')),     # Seperate App
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^disclaimer/', include('disclaimer.urls')),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'mark_attendance', include('mark_attendance.urls')),
    url(r'fetch_data', include('fetch_data.urls')),
    url(r'^terms_and_conditions', include('terms_and_conditions.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Smart_Attendance_System/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Smart_Attendance_System/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Dipesh Pal" content="">

    {% block title %}<title>SAS</title>{% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static '/css/business-frontpage.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Youmax Scripts -->
    <link href="{% static '/css/youmax.min.css' %}" rel="stylesheet" type="text/css">

     <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png"  href="https://i.ibb.co/kh9B5dC/logo.png" %}>


</head>

<body>
    <header class="site-header">
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'home:list' %}"><img src="media/logo/logo.png" style="height:50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                  <!---HOME--->
                    <li {% block homeli %} {% endblock %}>
                      <a class="nav-link" href="{% url 'home:list' %}">Home
                          <span class="sr-only">(current)</span>
                      </a>
                    </li>

                    <!--<li {% block videosli %} {% endblock %}>-->
                      <!--<a class="nav-link" href="/videos/videos.html">Videos</a>-->
                    <!--</li>-->

                  <!---Login / Signup / Logout--->
                  {% if user.is_authenticated%}
                        {% if user.is_staff %}
                         <li {% block mark_attendance %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/mark_attendance">Mark Attendance</a>
                         </li>
                        {% endif %}

                        <li {% block fetch_data %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/fetch_data">Check Attendance</a>
                        </li>

                        {% if user.is_superuser  %}
                          <li {% block articleCreateli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/create/">Create New Article</a>
                          </li>

                          <li {% block admin_cpanel %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/admin_cpanel/">Cpanel</a>
                          </li>
                        {% endif %}


                        <li {% block profileli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/accounts/profile/">Profile</a>
                        </li>

                        <li class="nav-item" >
                            <form id="logout_btn" action="/accounts/logout/" method="post">
                            {% csrf_token %}
                                <input type="hidden" name="logout" value="Logout" />
                                <a class="nav-link" onmouseover="this.style.cursor='hand'"
                                        onclick="document.getElementById('logout_btn').submit();">Logout
                                </a>
                            </form>
                        </li>
                  {% else %}
                    <li  {% block loginli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                    </li>
                    <li {% block signupli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/signup/">Sign Up</a>
                    </li>
                  {% endif %}
                  <!---End Login / Signup / Logout--->
                  <li {% block aboutli %} {% endblock %} class="nav-item">
                         <a class="nav-link" href="/about/about.html">About</a>
                  </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <!--==== SIDEBAR ====-->
        <!--<div class="col-md-4">-->
          <!--<div class="content-section">-->
            <!--<h3>Social Stats</h3>-->
            <!--<p class='text-muted'>Subscribe me on YouTube-->
              <!--<ul class="list-group">-->
                <!--<iframe height="80px" width="300px" frameborder="0" src="https://akshatmittal.com/youtube-realtime/embed/#!/UCGEoRAK92fUk2kY3kSJMR_Q" style="border: 0; width:300px; height:80px; background-color: #FFF;"></iframe>-->
              <!--</ul>-->
            <!--</p>-->
          <!--</div>-->
        <!--</div>-->
      </div>
    </main>


    <!-- Footer -->
    <footer class="py-5 bg-dark">
       <div align="center">
           <h2 id="text_about_heading" style="color: #ffffff; text-size: 5%">We are on Social</h2>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/YouTube.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Instagram.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Facebook.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Twitter.png"></a>
       </div>

      <div class="container">
          <!-- Bottom -->
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a href="/about/about.html" class="text-light">About</a>
            </li>

            <li class="list-inline-item">
                <a href="/disclaimer/disclaimer.html" class="text-light">Disclaimer</a>
            </li>

            <li class="list-inline-item">
                <a href="/contact_us/contact_us.html" class="text-light">Contact Us</a>
            </li>

            <li class="list-inline-item">
                <a href="/privacy_policy/privacy_policy.html" class="text-light">Privacy Policy</a>
            </li>

            <li class="list-inline-item">
                <a href="/terms_and_conditions" class="text-light">Terms and Conditions</a>
            </li>
          </ul>
      </div>
      <p class="m-0 text-center text-white">Copyright &copy; Smart Attendance System 2019-2020. All Rights Reserved</p>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Js min -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"></script>

    <script>
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                console.log(content)
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
             })
        })
    </script>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="/static/js/youmax.min.js" type="text/javascript"></script>

</body>
</html>

Smart_Attendance_System/templates/base_layout2.html
{% load static from staticfiles %}
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Dipesh Pal" content="">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png"  href="http://gdurl.com/jScY" %}>

    {% block title %}<title>SAS</title>{% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static '/css/business-frontpage.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--<script src="./jquery.min.js"></script>-->
	<script src="{% static '/jquery/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static '/js/youmax.js' %}"></script>
	<link href="{% static '/css/youmax.css' %}" rel="stylesheet" />

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png"  href="https://i.ibb.co/kh9B5dC/logo.png" %}>

    {% block script %} {% endblock %}
</head>

<body>
    <div class="bodydiv">
    <header>
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'home:list' %}"><img src="/media/logo/logo.png" style="height:50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                  <!---HOME--->
                  <li {% block homeli %} {% endblock %}>
                      <a class="nav-link" href="{% url 'home:list' %}">Home
                          <span class="sr-only">(current)</span>
                      </a>
                  </li>

                  <!--<li {% block videosli %} {% endblock %}>-->
                      <!--<a class="nav-link" href="/videos/videos.html">Videos-->
                          <!--&lt;!&ndash;<span class="sr-only">(current)</span>&ndash;&gt;-->
                      <!--</a>-->
                  <!--</li>-->

                  <!---Login / Signup / Logout--->
                  {% if user.is_authenticated%}
                        {% if user.is_staff %}
                         <li {% block mark_attendance %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/mark_attendance">Mark Attendance</a>
                         </li>
                        {% endif %}

                         <li {% block fetch_data %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/fetch_data">Check Attendance</a>
                         </li>

                        {% if user.is_superuser%}
                          <li {% block articleCreateli %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/create/">Create New Article</a>
                          </li>

                          <li {% block admin_cpanel %} {% endblock %} class="nav-item">
                                <a class="nav-link" href="/admin_cpanel/">Cpanel</a>
                          </li>
                        {% endif %}

                        <li {% block profileli %} {% endblock %} class="nav-item">
                              <a class="nav-link" href="/accounts/profile/">Profile</a>
                        </li>

                        <li class="nav-item" >
                            <form id="logout_btn" action="/accounts/logout/" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="logout" value="Logout" />
                                <a class="nav-link" onmouseover="this.style.cursor='hand'"
                                   onclick="document.getElementById('logout_btn').submit();">Logout
                                </a>
                            </form>
                        </li>
                  {% else %}
                    <li {% block loginli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                    </li>
                    <li {% block signupli %} {% endblock %} class="nav-item">
                        <a class="nav-link" href="/accounts/signup/">Sign Up</a>
                    </li>
                  {% endif %}
                  <!---End Login / Signup / Logout--->
                  <li {% block aboutli %} {% endblock %} class="nav-item">
                         <a class="nav-link" href="/about/about.html">About</a>
                  </li>

              </ul>
            </div>
          </div>
        </nav>
    </header>
        <div class="block_content_baseLayout2">
            {% block content %}
            {% endblock %}

            {% block head_extra %}
            {% endblock head_extra %}
        </div>
    </div>
    <br><br><br><br><br><br>

    <!-- Footer -->
   <footer class="py-5 bg-dark">
       <div align="center">
           <h2 id="text_about_heading" style="color: #ffffff; text-size: 5%">We are on Social</h2>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/YouTube.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Instagram.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Facebook.png"></a>
           <a href="#" target="_blank"><img style="max-width: 5%; height: 5%;" class="round-circle account-img" src="/media/social/Twitter.png"></a>
       </div>

      <div class="container">
          <!-- Bottom -->
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a href="/about/about.html" class="text-light">About</a>
            </li>

            <li class="list-inline-item">
                <a href="/disclaimer/disclaimer.html" class="text-light">Disclaimer</a>
            </li>

            <li class="list-inline-item">
                <a href="/contact_us/contact_us.html" class="text-light">Contact Us</a>
            </li>

            <li class="list-inline-item">
                <a href="/privacy_policy/privacy_policy.html" class="text-light">Privacy Policy</a>
            </li>

            <li class="list-inline-item">
                <a href="/terms_and_conditions" class="text-light">Terms and Conditions</a>
            </li>
          </ul>
      </div>
      <p class="m-0 text-center text-white">Copyright &copy; Smart Attendance System 2019-2020. All Rights Reserved</p>
    </footer>

     <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    

    <!-- Bootstrap core JavaScript -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Js min -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"></script>

    <script>
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                console.log(content)
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
             })
             $(".content-markdown img").each(function(){
                $(this).addClass("img-fluid")
             })
        })
    </script>
</body>
</html>

Smart_Attendance_System/templates/signup.html
{% extends 'base_layout2.html' %}


{% block title %}<title>SAS - SignUp</title>{% endblock %}

{% block signupli %} class="nav-item active" {% endblock %}

{% block content %}
    <div>
      <form class="site-form" method="post">
          <h1 class="h1">Signup</h1>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="SignUp">
      </form>
  </div>
{% endblock %}