Smart_Attendance_System/Smart_Attendance_System/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^face_recognition/', include('face_recognition.urls')),
    url(r'^admin_cpanel/', include('admin_cpanel.urls')),
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('accounts.urls')),
    url(r'^', include('home.urls')),     # Seperate App
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^disclaimer/', include('disclaimer.urls')),
    url(r'^privacy_policy/', include('privacy_policy.urls')),
    url(r'^contact_us/', include('contact_us.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'mark_attendance', include('mark_attendance.urls')),
    url(r'fetch_data', include('fetch_data.urls')),
    url(r'^terms_and_conditions', include('terms_and_conditions.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Smart_Attendance_System/home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/', views.article_update, name="post_edit"),
    url(r'^(?P<slug>[\w-]+)/delete/', views.article_delete, name="delete_post"),
]

Smart_Attendance_System/mark_attendance/urls.py
from django.conf.urls import url

from . import views

app_name = 'mark_attendance'

urlpatterns = [
    url(r'^success/$', views.mark_attendance_success, name="success"),
    url(r'^$', views.mark_attendance, name="mark_attendance"),
    url(r'^camera_attendance', views.camera_attendance, name="camera_attendance"),
]

Smart_Attendance_System/mark_attendance/models.py
from django.db import models


# Create your models here.
class UploadFile(models.Model):
    file = models.ImageField(blank=False, upload_to='check_images')

Smart_Attendance_System/mark_attendance/forms.py
from django import forms
from . import models


class UploadFile(forms.ModelForm):
    class Meta:
        model = models.UploadFile
        fields = ['file']

Smart_Attendance_System/mark_attendance/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from . import trigger


@login_required(login_url="/accounts/login/")
def mark_attendance(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = forms.UploadFile(request.POST, request.FILES)
            if form.is_valid():
                # save article to db
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                print("Calling Check Image -")
                trigger.start2()
                return render(request, 'mark_attendance/success.html')
        else:
            form = forms.UploadFile()
        return render(request, 'mark_attendance/mark_attendance.html', {'form': form})
    else:
        return render(request, 'mark_attendance/not_valid_user.html')


@login_required(login_url="/accounts/login/")
def mark_attendance_success(request):
    return render(request, 'mark_attendance/success.html')


@login_required(login_url="/accounts/login/")
def camera_attendance(request):
    # trigger.start_camera_attendance()
    trigger.start()
    return render(request, 'mark_attendance/success.html')

Smart_Attendance_System/mark_attendance/templates/mark_attendance/camera_attendance.html
{% extends 'base_layout2.html' %}

{% block mark_attendance %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Marked Attendance</h1>
    <p><b>Camera has been started in your system, one camera closed. It will mark attendance automatically</b></p>
{% endblock %}

Smart_Attendance_System/mark_attendance/templates/mark_attendance/mark_attendance.html
{% extends 'base_layout2.html' %}

{% block mark_attendance %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Mark Attendance by Submit Photo</h1>
    <p><b>Upload your Image to mark your attendance</b></p>
    <div class="create-article">
        <form class="site-form" action="{% url 'mark_attendance:mark_attendance' %}" method="post" enctype="multipart/form-data">
            <h2>Submit Your Image File (Only .png or .jpg)</h2>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <hr>
    <div class="create-article">
        <h1>Mark Attendance by Camera</h1>
        <a style="color: #3B5998" href="{% url 'mark_attendance:camera_attendance' %}">Click Here to start the camera</a>
    </div>
{% endblock %}

Smart_Attendance_System/mark_attendance/templates/mark_attendance/not_valid_user.html
{% extends 'base_layout2.html' %}


{% block mark_attendance %} class="nav-item active" {% endblock %}

{% block content %}
    <div class="create-article">
        <h1>You are not a valid user, contact administrator or go back to home</h1>
    </div>
{% endblock %}

Smart_Attendance_System/mark_attendance/templates/mark_attendance/success.html
{% extends 'base_layout2.html' %}

{% block mark_attendance %} class="nav-item active" {% endblock %}

{% block content %}
    <h1>Mark Attendance</h1>
    <p><b>Successfully Submitted</b></p>
{% endblock %}